routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Usercontroller;
use App\Http\Controllers\MoutonController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


//gestion des authentifications
Route::get('admin', [Usercontroller::class, 'index'])->name('admin')->middleware('admin');
Route::get('listEleveur', [Usercontroller::class, 'listEleveur'])->name('listEleveur')->middleware('admin');
Route::get('listClient', [Usercontroller::class, 'listClient'])->name('listClient')->middleware('admin');
Route::get('listAdmin', [Usercontroller::class, 'listAdmin'])->name('listAdmin')->middleware('admin');
Route::get('users/details/{id}', [Usercontroller::class, 'show'])->name('users.show')->middleware('admin');
Route::middleware(['auth'])->group(function () {

    Route::post('/users/block/{id}', [UserController::class, 'block'])->name('users.block');

    Route::post('/users/unblock/{id}', [UserController::class, 'unblock'])->name('users.unblock');
});

Route::resource('users', UserController::class)->only([
    'index', 'show', 'edit', 'update', 'destroy'
])->names([
    'index' => 'users.index',
    'show' => 'users.show',
    'edit' => 'users.edit',
    'update' => 'users.update',
    'destroy' => 'users.destroy',
]);




// Route::get('eleveur',function(){
//     return view('eleveur.eleveur');
// })->name('eleveur');

Route::get('indexByOwner',[MoutonController::class,'indexByOwner'])->name('indexByOwner')->middleware('eleveur');



Route::get('client',function(){
    return view('client.client');
})->name('client')->middleware('client');

//gestion des cruds

Route::resource('users', UserController::class);

//moutons
Route::middleware(['eleveur'])->group(function () {
    Route::resource('moutons', MoutonController::class)->only(['create', 'store', 'edit', 'update', 'destroy']);
});
Route::get('moutons', [MoutonController::class, 'index'])->name('moutons.index');
Route::get('moutons/{mouton}', [MoutonController::class, 'show'])->name('moutons.show');
Route::get('contact', [MoutonController::class, 'contact'])->name('contact');

resources/views/eleveur/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{asset('storage/css/styles.css')}}">
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
    <title>Liste moutons</title>
</head>

<body>
    <div class="side-menu">
        <div class="brand-name">
            <h1>Khar_bi</h1>
        </div>
        <ul>
            <li> <span><a href="">Dashboard</a></span> </li>
            <li><span><a href="">Add Sheep</a></span> </li>
            <li><span><a href="">Sheep List</a></span> </li>

        </ul>
    </div>
    <div class="container">
        <div class="header">
            <div class="nav">
                <div class="search">
                    <span></span>
                </div>
                <div class="user">
                    <div class="img-case">
                        <span></span>
                    </div>
                    <ul class="nav-item dropdown">
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->nom }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
        <br>
        <div class="content">
            <div class="content-2">
                <div class="recent-payments">
                    <div class="title">
                        <h2>Ajouter Un Mouton</h2>
                    </div>
                    <form method="POST" action="{{route('moutons.store')}}" enctype="multipart/form-data" class="mt-4">
                        @csrf

                        <div class="form-group">
                            <label for="nom">Nom du mouton</label>
                            <input type="text" id="nom" name="nom" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="race">Race du mouton</label>
                            <select id="race" name="race" class="form-control" required>
                                <option value="ladoum">Ladoum</option>
                                <option value="bali-bali">Bali-bali</option>
                                <option value="kharou-yar">Kharou yaar</option>
                                <option value="merinos">Mérinos</option>
                                <option value="romney">Romney</option>
                                <option value="suffolk">Suffolk</option>
                                <option value="dorset">Dorset</option>
                                <option value="shropshire">Shropshire</option>
                                <option value="cheviot">Cheviot</option>
                                <option value="border-leicester">Border Leicester</option>
                                <option value="corriedale">Corriedale</option>
                                <option value="lincoln">Lincoln</option>
                                <option value="clun-forest">Clun Forest</option>
                                <option value="columbia">Columbia</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="genealogie">Généalogie du mouton</label>
                            <textarea type="text" id="genealogie" name="genealogie" class="form-control" required cols="5" rows="5">

                            </textarea>

                        </div>

                        <div class="form-group">
                            <label for="photo">Photo du mouton</label>
                            <input type="file" id="photo" name="photo" class="form-control-file">
                        </div>

                        <div class="form-group">
                            <label for="taille">Taille du mouton (en cm)</label>
                            <input type="number" id="taille" name="taille" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="poids">Poids du mouton (en kg)</label>
                            <input type="number" id="poids" name="poids" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="prix">Prix du mouton (en francs)</label>
                            <input type="number" id="prix" name="prix" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="date_de_naissance">Date de naissance du mouton</label>
                            <input type="date" id="date_de_naissance" name="date_de_naissance" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <input type="number" id="proprietaire_id" name="proprietaire_id" value="{{ Auth::user()->id }}" hidden class="form-control" required>
                        </div>

                        <button type="submit" class="btn btn-primary">Ajouter le mouton</button>
                    </form>
                    <br>
                </div>
            </div>
            <br>
        </div>


    </div>
</body>

</html>

resources/views/eleveur/eleveur.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="favicon.png">

    <meta name="description" content="" />
    <meta name="keywords" content="bootstrap, bootstrap4" />

    <link
        href="https://fonts.googleapis.com/css2?family=Display+Playfair:wght@400;700&family=Inter:wght@400;700&display=swap"
        rel="stylesheet">


    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

    <link rel="stylesheet" href="{{ asset('storage/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/css/animate.min.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/css/jquery.fancybox.min.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/fonts/icomoon/style.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/fonts/flaticon/font/flaticon.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/css/aos.css') }}">
    <link rel="stylesheet" href="{{ asset('storage/css/style.css') }}">


    <title>Khar-Bi</title>
</head>

<body>

    <div class="site-mobile-menu">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close">
                <span class="icofont-close js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>



    <nav class="site-nav mb-5">
        <div class="pb-2 top-bar mb-3">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-6 col-lg-9">
                        <a href="#" class="small mr-3"><span class="icon-question-circle-o mr-2"></span> <span
                                class="d-none d-lg-inline-block">Vous avez des questions?</span></a>
                        <a href="#" class="small mr-3"><span class="icon-phone mr-2"></span> <span
                                class="d-none d-lg-inline-block">+221 77 702 60 66</span></a>
                        <a href="#" class="small mr-3"><span class="icon-envelope mr-2"></span> <span
                                class="d-none d-lg-inline-block">info@Khar-bi.com</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="sticky-nav js-sticky-header">
            <div class="container position-relative">
                <div class="site-navigation text-center">
                    <a href="/" class="logo menu-absolute m-0">Khar-Bi<span class="text-primary">.</span></a>

                    <ul class="js-clone-nav d-none d-lg-inline-block site-menu">
                        <li class="active"><a href="/">Home</a></li>

                        <li><a href="{{ route('moutons.create') }}">Ajouter un Mouton</a></li>
                        <li><a href="{{ route('indexByOwner') }}">Liste des moutons</a></li>

                    </ul>
                    &nbsp;&nbsp;
                    <a href="#" class="btn-book btn btn-secondary btn-sm">{{ Auth::user()->prenom }}</a>&nbsp;

                    <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                document.getElementById('logout-form').submit();"
                        class="btn-book btn btn-secondary btn-sm ">Deconnexion</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>


                    <a href="#"
                        class="burger ml-auto float-right site-menu-toggle js-menu-toggle d-inline-block d-lg-none light"
                        data-toggle="collapse" data-target="#main-navbar">
                        <span></span>
                    </a>
                    </ul>

                </div>
            </div>
        </div>
    </nav>


    <div class="untree_co-hero overlay" style="background-image: url('{{ asset('storage/images/Mouton.jpeg') }}">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12">
                    <div class="row justify-content-center ">
                        <div class="col-lg-6 text-center ">
                            <h1 class="mb-4 heading text-white" data-aos="fade-up" data-aos-delay="100">Liste de mes
                                Moutons</h1>

                        </div>


                    </div>

                </div>

            </div> <!-- /.row -->
        </div> <!-- /.container -->

    </div> <!-- /.untree_co-hero -->




      <div class="container">
        <div class="row">
            @foreach ($moutons as $mouton)
                <div class="col-lg-6 mb-4" data-aos="fade-up" data-aos-delay="100">
                    <div class="media-h d-flex h-100">
                        <figure>
                            <img src="{{ asset('storage/' . $mouton->photo) }}" alt="Image">
                        </figure>
                        <div class="media-h-body">
                            <h2 class="mb-3"><a
                                    href="{{ route('moutons.show', $mouton->id) }}">{{ $mouton->nom }}</a></h2>
                            <p>Race: {{ $mouton->race }}</p>
                            <p>Taille: {{ $mouton->taille }} cm</p>
                            <p>Poids: {{ $mouton->poids }} kg</p>
                            <p>Prix: {{ $mouton->prix }} francs</p>
                            <p>Date de naissance: {{ $mouton->date_de_naissance }}</p>
                            <a href="{{ route('moutons.show', $mouton->id) }}" class="btn btn-primary">Détails</a>
                            <a href="{{ route('moutons.edit', $mouton->id) }}" class="btn btn-warning">Éditer</a>
                            <form action="{{ route('moutons.destroy', $mouton->id) }}" method="POST"
                                style="display: inline-block;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('Êtes-vous sûr de supprimer ce mouton?')">Supprimer</button>
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach

            <div class="col-12 text-center">
                {{ $moutons->links() }} <!-- Affiche la pagination -->
            </div>

        </div>

        <div class="row mt-5">
            <div class="col-12 text-center">
                {{ $moutons->links() }}
            </div>
        </div>
    </div> 

    <!-- /.untree_co-section -->

    <div class="site-footer">


        <div class="container">

            <div class="row">
                <div class="col-lg-3 mr-auto">
                    <div class="widget">
                        <h3>A Propos de Nous<span class="text-primary">.</span> </h3>
                        <p>Chez Khar-bi.com, nous puisons dans notre riche héritage et notre expertise avérée pour
                            offrir des services d'assistance exceptionnels, guidant nos clients à travers les défis et
                            au-delà des frontières conventionnelles.</p>
                    </div> <!-- /.widget -->
                    <div class="widget">
                        <h3>Suivez nous sur les Réseaux sociaux</h3>
                        <ul class="list-unstyled social">
                            <li><a href="#"><span class="icon-instagram"></span></a></li>
                            <li><a href="#"><span class="icon-twitter"></span></a></li>
                            <li><a href="#"><span class="icon-facebook"></span></a></li>
                            <li><a href="#"><span class="icon-linkedin"></span></a></li>
                            <li><a href="#"><span class="icon-pinterest"></span></a></li>
                            <li><a href="#"><span class="icon-dribbble"></span></a></li>
                        </ul>
                    </div> <!-- /.widget -->
                </div> <!-- /.col-lg-3 -->

                <div class="col-lg-2 ml-auto">
                    <div class="widget">
                        <h3>Elevage</h3>
                        <ul class="list-unstyled float-left links">
                            <li><a href="#">Moutons</a></li>
                            <li><a href="#">Chèvres</a></li>
                            <li><a href="#">Poules</a></li>
                            <li><a href="#">Lapins</a></li>
                            <li><a href="#">Pigeons</a></li>
                        </ul>
                    </div> <!-- /.widget -->
                </div> <!-- /.col-lg-3 -->

                <div class="col-lg-3">
                    <div class="widget">
                        <h3>Gallery</h3>
                        <ul class="instafeed instagram-gallery list-unstyled">
                            <li><a class="instagram-item" href="{{ asset('storage/images/mouton1.webp') }}"
                                    data-fancybox="gal"><img src="{{ asset('storage/images/mouton1.webp') }}" alt="" width="72"
                                        height="72"></a>
                            </li>
                            <li><a class="instagram-item" href="{{ asset('storage/images/mouton2.webp') }}"
                                    data-fancybox="gal"><img src="{{ asset('storage/images/mouton2.webp') }}" alt="" width="72"
                                        height="72"></a>
                            </li>
                            <li><a class="instagram-item" href="{{ asset('storage/images/mouton3.webp') }}"
                                    data-fancybox="gal"><img src="{{ asset('storage/images/mouton3.webp') }}" alt="" width="72"
                                        height="72"></a>
                            </li>
                            <li><a class="instagram-item" href="{{ asset('storage/images/mouton4.webp') }}"
                                    data-fancybox="gal"><img src="{{ asset('storage/images/mouton4.webp') }}" alt="" width="72"
                                        height="72"></a>
                            </li>
                            <li><a class="instagram-item" href="{{ asset('storage/images/mouton5.webp') }}"
                                    data-fancybox="gal"><img src="{{ asset('storage/images/mouton5.webp') }}" alt="" width="72"
                                        height="72"></a>
                            </li>
                            <li><a class="instagram-item" href="{{ asset('storage/images/mouton6.webp') }}"
                                    data-fancybox="gal"><img src="{{ asset('storage/images/mouton6.webp') }}" alt="" width="72"
                                        height="72"></a>
                            </li>
                        </ul>
                    </div> <!-- /.widget -->
                </div> <!-- /.col-lg-3 -->


                <div class="col-lg-3">
                    <div class="widget">
                        <h3>Contact</h3>
                        <address>Yeumbeul-Nord, Cité Comico 4 extension</address>
                        <ul class="list-unstyled links mb-4">
                            <li><a href="tel://11234567890">+221 77 702 60 66</a></li>
                            <li><a href="tel://11234567890">+221 77 702 60 66</a></li>
                            <li><a href="mailto:info@mydomain.com">info@Khar-bi.com</a></li>
                        </ul>
                    </div> <!-- /.widget -->
                </div> <!-- /.col-lg-3 -->

            </div> <!-- /.row -->

            <div class="row mt-5">
                <div class="col-12 text-center">
                    <p class="copyright">Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>. Tous les Droits sont Reservés. &mdash; Designed with love by <a
                            href="">Serigne Cheikh NDAO</a> Distributed By <a
                            href="https://themewagon.com">ThemeWagon</a>
                        <!-- License information: https://untree.co/license/ -->
                </div>
            </div>
        </div> <!-- /.container -->
    </div> <!-- /.site-footer -->

    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <script src="{{ asset('storage/js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ asset('storage/js/popper.min.js') }}"></script>
    <script src="{{ asset('storage/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('storage/js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('storage/js/jquery.animateNumber.min.js') }}"></script>
    <script src="{{ asset('storage/js/jquery.waypoints.min.js') }}"></script>
    <script src="{{ asset('storage/js/jquery.fancybox.min.js') }}"></script>
    <script src="{{ asset('storage/js/jquery.sticky.js') }}"></script>
    <script src="{{ asset('storage/js/aos.js') }}"></script>
    <script src="{{ asset('storage/js/custom.js') }}"></script>


</body>

</html>